// ═══════════════════════════════════════════════════════════════════
//  config.js – Beghou 2026 Firm Building Initiatives Dashboard
//  Data model: Workstreams (atomic unit) grouped by Initiative
// ═══════════════════════════════════════════════════════════════════

const CONFIG = {
  clientId:    '8abbd6c0-4717-4220-b6c1-a38dae7c3a14',
  tenantId:    '4854ac27-6418-4983-9efc-93545436d559',
  redirectUri: 'https://conroy-patrick.github.io/2026-firm-building-initiatives/',
  graphEndpoint: 'https://graph.microsoft.com/v1.0',
  siteHostname:  'beghouconsultinginc-my.sharepoint.com',
  sitePath:      '/personal/aaron_mccracken_beghouconsulting_com',
  workstreamListName: '2026 Workstream Tracker',
  updatesListName:    'Workstream Updates',
  fiscalYearStart: new Date('2026-01-01'),
  fiscalYearEnd:   new Date('2026-12-31'),
  refreshIntervalMs: 5 * 60 * 1000
};

CONFIG.expectedProgress = (() => {
  const now = new Date(), start = CONFIG.fiscalYearStart, end = CONFIG.fiscalYearEnd;
  return Math.round((Math.max(0, Math.min(now - start, end - start)) / (end - start)) * 100);
})();

// ── Initiative metadata (grouping + display only) ──────────────────
const INITIATIVE_META = [
  { title: 'Bookings Sufficient to Achieve Target',       category: 'Revenue & Operations', partner: 'Dennis',           execSponsor: 'MR' },
  { title: 'Commercial Infrastructure & Sustainable Growth', category: 'Revenue & Operations', partner: 'Clare',         execSponsor: 'MR' },
  { title: 'Effective Workforce Planning & Deployment',   category: 'Revenue & Operations', partner: 'Kevin',            execSponsor: 'MR' },
  { title: 'Deliverable Quality',                         category: 'Revenue & Operations', partner: 'TBD',              execSponsor: 'MR' },
  { title: 'AI Strategy for Internal Use (L1\u2013L3)',   category: 'Revenue & Operations', partner: 'Nicole',           execSponsor: 'MR' },
  { title: 'Future-Proofing Data Management Offering',    category: 'Product & Tech',       partner: 'Piotr',            execSponsor: 'DC' },
  { title: 'Technology Strategy for Scale & Profit',      category: 'Product & Tech',       partner: 'Jason',            execSponsor: 'DC' },
  { title: 'Optimizing Arc Data Management Delivery',     category: 'Product & Tech',       partner: 'Justin',           execSponsor: 'DC' },
  { title: 'Beghou Unified Systems Success',              category: 'Systems & People',     partner: 'Yair (w/ Michael)',execSponsor: 'MG' },
  { title: 'Develop Our Talent Infrastructure',           category: 'Systems & People',     partner: 'Dan S (w/ Ali)',   execSponsor: 'AF' }
];

// ── Seed Workstreams (~5 per initiative, 50 total) ─────────────────
const SEED_WORKSTREAMS = [

  // ── Initiative 1: Bookings Sufficient to Achieve Target ───────
  { id:1,  initiative:'Bookings Sufficient to Achieve Target', category:'Revenue & Operations',
    title:'ACV Methodology & Bookings Targets', owner:'Caden R.',
    status:'On Track', percentComplete:40,
    q1Goals:'Define ACV methodology and align with finance; set H1 bookings targets',
    q2Goals:'Methodology ratified by leadership; targets embedded in partner scorecards',
    q3Goals:'Mid-year review complete; H2 targets updated based on actuals',
    latestComment:'ACV methodology finalized and approved. Bookings targets set for all partners. Bi-weekly pipeline review cadence established.',
    lastUpdatedBy:'Caden R.', modified:'2026-04-08' },

  { id:2,  initiative:'Bookings Sufficient to Achieve Target', category:'Revenue & Operations',
    title:'Pipeline Management Framework', owner:'Caden R.',
    status:'On Track', percentComplete:25,
    q1Goals:'Baseline current pipeline health; define stage criteria and coverage ratio targets',
    q2Goals:'Pipeline review framework live; stage criteria adopted by all partners',
    q3Goals:'Coverage ratio consistently at 2x+; pipeline data feeding KPI dashboard',
    latestComment:'Pipeline health baseline complete — coverage ratio currently 2.1x target. Stage criteria drafted and circulating for partner review.',
    lastUpdatedBy:'Caden R.', modified:'2026-03-28' },

  { id:3,  initiative:'Bookings Sufficient to Achieve Target', category:'Revenue & Operations',
    title:'RFP Tracking & Win/Loss Reporting', owner:'Caden R.',
    status:'On Track', percentComplete:20,
    q1Goals:'Implement RFP log; track # received, submitted, won/lost',
    q2Goals:'RFP win rate baseline established; competitive debrief process live',
    q3Goals:'Win rate trending upward; debrief insights feeding proposal improvements',
    latestComment:'RFP tracking template shared with BD team. 3 RFPs logged in Q1. Win/loss debrief process being piloted.',
    lastUpdatedBy:'Caden R.', modified:'2026-03-15' },

  { id:4,  initiative:'Bookings Sufficient to Achieve Target', category:'Revenue & Operations',
    title:'New Logo Acquisition Strategy', owner:'Dennis P.',
    status:'On Track', percentComplete:30,
    q1Goals:'Identify target account list; define ICP and outreach approach',
    q2Goals:'Outreach program active; 5+ new logo opportunities in pipeline',
    q3Goals:'2+ new logos closed; lessons learned feeding H2 approach',
    latestComment:'Target account list of 18 companies finalized. ICP defined. 3 qualified new logo opportunities in active pipeline.',
    lastUpdatedBy:'Dennis P.', modified:'2026-04-05' },

  { id:5,  initiative:'Bookings Sufficient to Achieve Target', category:'Revenue & Operations',
    title:'Bookings KPI Dashboard', owner:'Caden R.',
    status:'At Risk', percentComplete:15,
    q1Goals:'Define KPI set; identify data sources; build dashboard v1',
    q2Goals:'Dashboard live and reviewed in monthly leadership meetings',
    q3Goals:'Dashboard fully adopted; data driving decisions',
    latestComment:'KPI definition complete but dashboard build delayed — HubSpot data gaps making pipeline reporting unreliable. At risk of missing Q2 milestone.',
    lastUpdatedBy:'Caden R.', modified:'2026-04-10' },

  // ── Initiative 2: Commercial Infrastructure & Sustainable Growth ─
  { id:6,  initiative:'Commercial Infrastructure & Sustainable Growth', category:'Revenue & Operations',
    title:'Sales Operations Audit & Redesign', owner:'Mudit S.',
    status:'On Track', percentComplete:30,
    q1Goals:'Complete sales ops audit; document current state gaps',
    q2Goals:'Redesigned sales ops model approved; implementation begun',
    q3Goals:'New sales ops model fully operational',
    latestComment:'Audit complete. Key gaps: inconsistent account planning, no pricing playbook, limited BD support infrastructure. Redesign proposals drafted.',
    lastUpdatedBy:'Mudit S.', modified:'2026-04-02' },

  { id:7,  initiative:'Commercial Infrastructure & Sustainable Growth', category:'Revenue & Operations',
    title:'RFP Excellence Program', owner:'Adriana V.',
    status:'On Track', percentComplete:20,
    q1Goals:'Assess current RFP process; identify improvement areas',
    q2Goals:'RFP templates and review process live; training complete',
    q3Goals:'RFP quality scores improving; win rate trending up',
    latestComment:'RFP process assessment complete. Template library being built. Proposal review checklist drafted — piloting on next 2 RFPs.',
    lastUpdatedBy:'Adriana V.', modified:'2026-03-25' },

  { id:8,  initiative:'Commercial Infrastructure & Sustainable Growth', category:'Revenue & Operations',
    title:'Solution Architect Role Definition', owner:'Clare M.',
    status:'At Risk', percentComplete:10,
    q1Goals:'Define SA role requirements; get headcount approved',
    q2Goals:'SA hired or identified internally; embedded in sales process',
    q3Goals:'SA contributing to deal shaping and win rate improvement',
    latestComment:'Role requirements defined but headcount approval stalled at leadership level. Escalation needed — this is blocking Q2 milestone.',
    lastUpdatedBy:'Clare M.', modified:'2026-04-10' },

  { id:9,  initiative:'Commercial Infrastructure & Sustainable Growth', category:'Revenue & Operations',
    title:'Sales Training Program', owner:'Luke B.',
    status:'Not Started', percentComplete:0,
    q1Goals:'Define training needs; identify facilitators',
    q2Goals:'Training curriculum built; first cohort trained',
    q3Goals:'All client-facing staff trained; skills assessment complete',
    latestComment:'On hold pending SA role definition. Will kick off once headcount decision is made.',
    lastUpdatedBy:'Clare M.', modified:'2026-04-10' },

  { id:10, initiative:'Commercial Infrastructure & Sustainable Growth', category:'Revenue & Operations',
    title:'Pricing Discipline & Account Planning', owner:'Adriana V.',
    status:'On Track', percentComplete:15,
    q1Goals:'Document current pricing variability; define guardrails',
    q2Goals:'Pricing playbook v1 published; account planning templates live',
    q3Goals:'Consistent pricing across all accounts; account plans reviewed quarterly',
    latestComment:'Pricing variability analysis complete — significant range across accounts identified. Guardrails being drafted with finance.',
    lastUpdatedBy:'Adriana V.', modified:'2026-03-30' },

  // ── Initiative 3: Effective Workforce Planning & Deployment ──────
  { id:11, initiative:'Effective Workforce Planning & Deployment', category:'Revenue & Operations',
    title:'Pod Model Design & Rollout', owner:'Luke B.',
    status:'On Track', percentComplete:75,
    q1Goals:'Design pod model structure; present to leadership for alignment',
    q2Goals:'Pod model V2 finalized; all workstreams complete by 5/31',
    q3Goals:'Pod model fully implemented across all accounts',
    latestComment:'Pod Model V2 75% complete — due 4/15. Structure finalized: pods of 4-6 by solution area. Manager briefing April 27th.',
    lastUpdatedBy:'Luke B.', modified:'2026-04-07' },

  { id:12, initiative:'Effective Workforce Planning & Deployment', category:'Revenue & Operations',
    title:'Staffing Governance Framework', owner:'Aaron M.',
    status:'On Track', percentComplete:50,
    q1Goals:'Define staffing governance principles and decision rights',
    q2Goals:'Governance framework approved; staffing process redesigned',
    q3Goals:'New staffing process fully adopted; compliance tracked',
    latestComment:'Governance framework draft complete. Decision rights matrix reviewed with Kevin. Staffing process redesign underway.',
    lastUpdatedBy:'Aaron M.', modified:'2026-03-24' },

  { id:13, initiative:'Effective Workforce Planning & Deployment', category:'Revenue & Operations',
    title:'Performance Management Redesign', owner:'Dan K.',
    status:'On Track', percentComplete:35,
    q1Goals:'Assess current PM process gaps; define new framework',
    q2Goals:'New PM framework approved; manager training complete',
    q3Goals:'First PM cycle on new framework complete',
    latestComment:'Current state assessment complete. New framework draft incorporates clear expectations by level and quarterly check-in cadence.',
    lastUpdatedBy:'Dan K.', modified:'2026-03-20' },

  { id:14, initiative:'Effective Workforce Planning & Deployment', category:'Revenue & Operations',
    title:'US-India Collaboration Model', owner:'Luke B.',
    status:'On Track', percentComplete:25,
    q1Goals:'Document current US-India collaboration pain points; define target model',
    q2Goals:'New collaboration model piloted on 2 accounts',
    q3Goals:'Model adopted firm-wide; utilization and quality metrics on target',
    latestComment:'Pain point interviews complete across 6 accounts. Target model draft: pod-level India integration with clear RACI. Pilot account selection underway.',
    lastUpdatedBy:'Luke B.', modified:'2026-03-18' },

  { id:15, initiative:'Effective Workforce Planning & Deployment', category:'Revenue & Operations',
    title:'Change Management & Communications', owner:'Aaron M.',
    status:'On Track', percentComplete:40,
    q1Goals:'Develop change management plan; align leadership on communications approach',
    q2Goals:'Manager communications complete; All Hands delivered',
    q3Goals:'Staff adoption tracked; change feedback loops active',
    latestComment:'Change management plan approved. Manager meeting April 27th, All Hands May 5th. FAQ doc drafted.',
    lastUpdatedBy:'Aaron M.', modified:'2026-04-07' },

  // ── Initiative 4: Deliverable Quality ────────────────────────────
  { id:16, initiative:'Deliverable Quality', category:'Revenue & Operations',
    title:'Accountable Partner & Team Formation', owner:'TBD',
    status:'Behind', percentComplete:0,
    q1Goals:'Identify and confirm accountable partner; assemble core team',
    q2Goals:'Team fully resourced; workstream kickoffs complete',
    q3Goals:'All workstreams on track',
    latestComment:'Q1 goal not completed — partner not yet assigned. MR to resolve by end of April.',
    lastUpdatedBy:'MR', modified:'2026-04-09' },

  { id:17, initiative:'Deliverable Quality', category:'Revenue & Operations',
    title:'Knowledge Management Platform', owner:'TBD',
    status:'Behind', percentComplete:0,
    q1Goals:'Evaluate platform options; select and procure',
    q2Goals:'Platform live; content migration begun',
    q3Goals:'Knowledge base populated and actively used',
    latestComment:'Blocked pending partner assignment.',
    lastUpdatedBy:'MR', modified:'2026-04-09' },

  { id:18, initiative:'Deliverable Quality', category:'Revenue & Operations',
    title:'QC Process & Standards Design', owner:'TBD',
    status:'Behind', percentComplete:0,
    q1Goals:'Document current QC gaps; design standard review process',
    q2Goals:'QC framework approved; pilot on 3 accounts',
    q3Goals:'QC process adopted firm-wide; quality scores tracked',
    latestComment:'Blocked pending partner assignment.',
    lastUpdatedBy:'MR', modified:'2026-04-09' },

  { id:19, initiative:'Deliverable Quality', category:'Revenue & Operations',
    title:'Solutions Templates Library', owner:'TBD',
    status:'Not Started', percentComplete:5,
    q1Goals:'Inventory existing templates; identify gaps',
    q2Goals:'Core template library built and published',
    q3Goals:'Templates used on 80%+ of projects',
    latestComment:'Some existing templates inventoried by practice leads. Full workstream blocked pending partner assignment.',
    lastUpdatedBy:'MR', modified:'2026-04-09' },

  { id:20, initiative:'Deliverable Quality', category:'Revenue & Operations',
    title:'Training Program Development', owner:'TBD',
    status:'Not Started', percentComplete:0,
    q1Goals:'Define training curriculum; identify facilitators',
    q2Goals:'Training program launched; first cohort complete',
    q3Goals:'All staff trained; ongoing program established',
    latestComment:'Not yet started. Blocked pending partner assignment.',
    lastUpdatedBy:'MR', modified:'2026-04-09' },

  // ── Initiative 5: AI Strategy for Internal Use ───────────────────
  { id:21, initiative:'AI Strategy for Internal Use (L1\u2013L3)', category:'Revenue & Operations',
    title:'AI Tool Inventory & Assessment', owner:'Sharath N.',
    status:'On Track', percentComplete:50,
    q1Goals:'Survey all staff on AI tool usage; build inventory',
    q2Goals:'Approved tool list published; shadow IT eliminated',
    q3Goals:'100% of AI usage on approved platforms',
    latestComment:'Survey complete: 67% of staff using at least one AI tool, 11 distinct tools identified. Consolidating to 4 approved platforms.',
    lastUpdatedBy:'Sharath N.', modified:'2026-04-06' },

  { id:22, initiative:'AI Strategy for Internal Use (L1\u2013L3)', category:'Revenue & Operations',
    title:'Risk Guardrail Framework', owner:'Nicole B.',
    status:'On Track', percentComplete:45,
    q1Goals:'Draft risk guardrails covering data privacy, client confidentiality, output QC',
    q2Goals:'Guardrails approved; training complete',
    q3Goals:'Compliance tracked; guardrails updated based on emerging risks',
    latestComment:'Risk guardrail framework v1 approved by leadership. Training materials in development.',
    lastUpdatedBy:'Nicole B.', modified:'2026-04-06' },

  { id:23, initiative:'AI Strategy for Internal Use (L1\u2013L3)', category:'Revenue & Operations',
    title:'AI Toolkit Standardization', owner:'Sharath N.',
    status:'On Track', percentComplete:25,
    q1Goals:'Define approved toolkit by role and use case',
    q2Goals:'Standardized toolkits deployed; onboarding updated',
    q3Goals:'Toolkit adoption at 90%+; usage data informing updates',
    latestComment:'Toolkit requirements by role drafted. Vendor negotiations for enterprise licenses underway.',
    lastUpdatedBy:'Sharath N.', modified:'2026-03-28' },

  { id:24, initiative:'AI Strategy for Internal Use (L1\u2013L3)', category:'Revenue & Operations',
    title:'L1\u2013L3 Workflow Automation', owner:'Sharath N.',
    status:'On Track', percentComplete:15,
    q1Goals:'Identify and prioritize top L1 automation opportunities',
    q2Goals:'Top 3 L1 workflows automated; L2 opportunities scoped',
    q3Goals:'L1 automation fully deployed; L2 pilots live',
    latestComment:'Priority L1 workflows identified: report generation, data QC checks, meeting summarization. Build plan in progress.',
    lastUpdatedBy:'Sharath N.', modified:'2026-03-20' },

  { id:25, initiative:'AI Strategy for Internal Use (L1\u2013L3)', category:'Revenue & Operations',
    title:'Knowledge Sharing & Community of Practice', owner:'Nicole B.',
    status:'On Track', percentComplete:20,
    q1Goals:'Establish AI CoP; define knowledge sharing cadence',
    q2Goals:'Monthly AI learning sessions running; Slack channel active',
    q3Goals:'CoP self-sustaining; peer learning reducing onboarding time',
    latestComment:'AI Community of Practice launched with 24 founding members. First session scheduled for April 22nd.',
    lastUpdatedBy:'Nicole B.', modified:'2026-04-04' },

  // ── Initiative 6: Future-Proofing Data Management Offering ────────
  { id:26, initiative:'Future-Proofing Data Management Offering', category:'Product & Tech',
    title:'Competitive Landscape Analysis', owner:'Piotr W.',
    status:'On Track', percentComplete:35,
    q1Goals:'Complete competitive review of Veeva, IQVIA, Symphony DM offerings',
    q2Goals:'Competitive positioning document approved; gaps identified',
    q3Goals:'Competitive insights embedded in sales and product roadmap',
    latestComment:'Competitive review complete across 5 vendors. Three key gaps identified: Databricks integration, AI-assisted validation, modern MDM stack.',
    lastUpdatedBy:'Piotr W.', modified:'2026-04-05' },

  { id:27, initiative:'Future-Proofing Data Management Offering', category:'Product & Tech',
    title:'Databricks Migration Roadmap', owner:'Piotr W.',
    status:'On Track', percentComplete:20,
    q1Goals:'Assess current client Databricks needs; define migration path',
    q2Goals:'Databricks migration playbook published; first client pilot scoped',
    q3Goals:'Playbook in active use; 2+ clients on migration path',
    latestComment:'Client needs assessment complete — 4 of 8 active DM clients have Databricks in their environment. Migration playbook outline drafted.',
    lastUpdatedBy:'Piotr W.', modified:'2026-03-28' },

  { id:28, initiative:'Future-Proofing Data Management Offering', category:'Product & Tech',
    title:'MDM Modernization Plan', owner:'TBD',
    status:'Not Started', percentComplete:5,
    q1Goals:'Assess current MDM delivery approach; identify modernization opportunities',
    q2Goals:'Modernization roadmap defined; resource plan approved',
    q3Goals:'First modernized MDM delivery in market',
    latestComment:'Preliminary scoping done by Piotr. Dedicated owner needed to drive execution.',
    lastUpdatedBy:'Piotr W.', modified:'2026-03-10' },

  { id:29, initiative:'Future-Proofing Data Management Offering', category:'Product & Tech',
    title:'AI-Assisted Data Validation', owner:'TBD',
    status:'Not Started', percentComplete:5,
    q1Goals:'Define AI validation use cases; assess build vs. buy',
    q2Goals:'Prototype built; client feedback gathered',
    q3Goals:'AI validation capability in production on 1+ client',
    latestComment:'Use cases documented by Piotr. Awaiting owner assignment and resource allocation.',
    lastUpdatedBy:'Piotr W.', modified:'2026-03-10' },

  { id:30, initiative:'Future-Proofing Data Management Offering', category:'Product & Tech',
    title:'Client Delivery Commitment Mapping', owner:'Piotr W.',
    status:'On Track', percentComplete:15,
    q1Goals:'Map all active DM client commitments to 2026 roadmap capabilities',
    q2Goals:'Gaps resolved or escalated; commitments tracked in delivery dashboard',
    q3Goals:'No unresolved commitment gaps; client satisfaction maintained',
    latestComment:'Client interviews complete with 4 accounts. Commitment mapping 40% done — 2 gap areas identified requiring roadmap acceleration.',
    lastUpdatedBy:'Piotr W.', modified:'2026-04-01' },

  // ── Initiative 7: Technology Strategy for Scale & Profit ──────────
  { id:31, initiative:'Technology Strategy for Scale & Profit', category:'Product & Tech',
    title:'Technology Asset Inventory', owner:'Jason K.',
    status:'On Track', percentComplete:40,
    q1Goals:'Inventory all reusable technology components across Arc, Mainsail, IC',
    q2Goals:'Asset inventory published; reuse library accessible to all teams',
    q3Goals:'Reuse rate tracked; new builds referencing library first',
    latestComment:'Inventory complete: 14 reusable components identified. Categorized by maturity and applicability. Library being formatted for publication.',
    lastUpdatedBy:'Jason K.', modified:'2026-04-04' },

  { id:32, initiative:'Technology Strategy for Scale & Profit', category:'Product & Tech',
    title:'ROI Framework & Modeling', owner:'Jason K.',
    status:'On Track', percentComplete:25,
    q1Goals:'Define ROI methodology for technology investments; align with finance',
    q2Goals:'ROI models built for top 5 technology candidates',
    q3Goals:'ROI framework embedded in all new technology decisions',
    latestComment:'ROI framework draft complete and under review with DC and finance. Methodology covers build cost, reuse savings, and margin impact.',
    lastUpdatedBy:'Jason K.', modified:'2026-04-04' },

  { id:33, initiative:'Technology Strategy for Scale & Profit', category:'Product & Tech',
    title:'Roadmap Prioritization Process', owner:'Jason K.',
    status:'On Track', percentComplete:20,
    q1Goals:'Define prioritization criteria; score existing roadmap candidates',
    q2Goals:'Prioritized roadmap published; top 3 candidates in active development',
    q3Goals:'Prioritization process adopted for all new technology requests',
    latestComment:'Prioritization criteria defined: strategic fit, ROI, feasibility, time-to-value. Scoring top 20 candidates now.',
    lastUpdatedBy:'Jason K.', modified:'2026-03-25' },

  { id:34, initiative:'Technology Strategy for Scale & Profit', category:'Product & Tech',
    title:'Reusable Technology Development', owner:'TBD',
    status:'Not Started', percentComplete:0,
    q1Goals:'Select top 2 reusable technology candidates; begin scoping',
    q2Goals:'Development underway on priority components',
    q3Goals:'At least 1 reusable component deployed across 2+ clients',
    latestComment:'Pending roadmap prioritization completion and resource allocation approval.',
    lastUpdatedBy:'Jason K.', modified:'2026-04-04' },

  { id:35, initiative:'Technology Strategy for Scale & Profit', category:'Product & Tech',
    title:'Profit Impact Measurement', owner:'Jason K.',
    status:'On Track', percentComplete:10,
    q1Goals:'Define metrics for technology leverage on margin',
    q2Goals:'Baseline margin impact established; tracking live',
    q3Goals:'Technology leverage contributing measurably to firm margin',
    latestComment:'Metrics defined in collaboration with finance. Baseline measurement plan drafted — will kick off once asset inventory is published.',
    lastUpdatedBy:'Jason K.', modified:'2026-03-20' },

  // ── Initiative 8: Optimizing Arc Data Management Delivery ─────────
  { id:36, initiative:'Optimizing Arc Data Management Delivery', category:'Product & Tech',
    title:'Training Curriculum Development', owner:'Justin L.',
    status:'On Track', percentComplete:55,
    q1Goals:'Define curriculum; pilot with first cohort of 8 associates',
    q2Goals:'Curriculum finalized; all new DM hires trained on onboarding',
    q3Goals:'Training program self-sustaining; quality scores improving',
    latestComment:'Curriculum piloted with 8 associates — strong feedback (4.4/5 avg). Modules 1-4 finalized; modules 5-6 in review.',
    lastUpdatedBy:'Justin L.', modified:'2026-04-07' },

  { id:37, initiative:'Optimizing Arc Data Management Delivery', category:'Product & Tech',
    title:'Strategic Hiring Plan', owner:'Justin L.',
    status:'On Track', percentComplete:45,
    q1Goals:'Finalize hiring plan; get headcount approved',
    q2Goals:'4 DM roles filled; India team expanded',
    q3Goals:'Full delivery capacity online; utilization on target',
    latestComment:'Hiring plan approved: 4 new DM roles in H1. JDs posted; 2 candidates in final rounds.',
    lastUpdatedBy:'Justin L.', modified:'2026-04-07' },

  { id:38, initiative:'Optimizing Arc Data Management Delivery', category:'Product & Tech',
    title:'Delivery Center Launch', owner:'Justin L.',
    status:'On Track', percentComplete:30,
    q1Goals:'Finalize delivery center location and operating model',
    q2Goals:'Pilot launch May 1st; first client engaged',
    q3Goals:'Delivery center at full capacity; efficiency metrics on target',
    latestComment:'Operating model finalized. Delivery center pilot launches May 1st with 2 client engagements.',
    lastUpdatedBy:'Justin L.', modified:'2026-04-07' },

  { id:39, initiative:'Optimizing Arc Data Management Delivery', category:'Product & Tech',
    title:'Resource Planning Model', owner:'Justin L.',
    status:'On Track', percentComplete:25,
    q1Goals:'Design resource planning model; integrate with capacity planning tools',
    q2Goals:'Resource model operational; integrated with Ruddr',
    q3Goals:'Resource utilization at target; over/under-staffing eliminated',
    latestComment:'Resource model design complete. Integration with Ruddr scoped and in backlog.',
    lastUpdatedBy:'Justin L.', modified:'2026-03-30' },

  { id:40, initiative:'Optimizing Arc Data Management Delivery', category:'Product & Tech',
    title:'Efficiency Metrics & Continuous Improvement', owner:'Justin L.',
    status:'On Track', percentComplete:20,
    q1Goals:'Define DM delivery efficiency KPIs; build tracking mechanism',
    q2Goals:'Metrics baseline established; monthly review cadence live',
    q3Goals:'Efficiency improving quarter-over-quarter; insights driving process changes',
    latestComment:'KPIs defined: cycle time, rework rate, client satisfaction, utilization. Tracking mechanism in build.',
    lastUpdatedBy:'Justin L.', modified:'2026-03-22' },

  // ── Initiative 9: Beghou Unified Systems Success ──────────────────
  { id:41, initiative:'Beghou Unified Systems Success', category:'Systems & People',
    title:'System Requirements & Architecture', owner:'Yair S.',
    status:'On Track', percentComplete:35,
    q1Goals:'Finalize system requirements with all stakeholders; approve integration architecture',
    q2Goals:'Requirements locked; architecture approved and development underway',
    q3Goals:'All systems integrated; architecture validated in production',
    latestComment:'Requirements 90% finalized. Integration architecture approved. Time capture module scoping revealed unexpected complexity — 3-week impact.',
    lastUpdatedBy:'Yair S.', modified:'2026-04-09' },

  { id:42, initiative:'Beghou Unified Systems Success', category:'Systems & People',
    title:'Vendor Selection & Management', owner:'Yair S.',
    status:'On Track', percentComplete:30,
    q1Goals:'Complete vendor evaluation; select Ruddr + Sage Intacct; contract executed',
    q2Goals:'Vendor onboarding complete; delivery milestones tracking on schedule',
    q3Goals:'Vendor delivering on commitments; go-live on track',
    latestComment:'Vendor selected and contracts executed. Ruddr and Sage Intacct implementation teams onboarded. First sprint review April 18th.',
    lastUpdatedBy:'Yair S.', modified:'2026-04-02' },

  { id:43, initiative:'Beghou Unified Systems Success', category:'Systems & People',
    title:'HubSpot \u2192 Sage Intacct Integration', owner:'Patrick C.',
    status:'At Risk', percentComplete:20,
    q1Goals:'Complete field mapping; begin API integration development',
    q2Goals:'Integration tested and validated; revenue recognition automated',
    q3Goals:'Integration live in production; finance team adopted',
    latestComment:'Field mapping complete. API development started but scope has grown — deal attribution complexity adding time. Flagging At Risk.',
    lastUpdatedBy:'Patrick C.', modified:'2026-04-09' },

  { id:44, initiative:'Beghou Unified Systems Success', category:'Systems & People',
    title:'Time Capture & Resource Management', owner:'Luke B.',
    status:'At Risk', percentComplete:10,
    q1Goals:'Define time capture requirements; align with pod model design',
    q2Goals:'Time capture module configured and piloted',
    q3Goals:'Time capture live firm-wide; data feeding capacity planning',
    latestComment:'Requirements gathering revealed significant complexity with pod model intersection. Estimating additional 3 weeks. At Risk.',
    lastUpdatedBy:'Luke B.', modified:'2026-04-09' },

  { id:45, initiative:'Beghou Unified Systems Success', category:'Systems & People',
    title:'Go-Live & Adoption Program', owner:'Michael G.',
    status:'Not Started', percentComplete:0,
    q1Goals:'Design go-live plan; develop training materials',
    q2Goals:'Training delivered to all users; hypercare period planned',
    q3Goals:'Full adoption achieved; hypercare closed; system stable',
    latestComment:'Go-live plan design not yet started — will begin once integration timelines are confirmed.',
    lastUpdatedBy:'Yair S.', modified:'2026-04-02' },

  // ── Initiative 10: Develop Our Talent Infrastructure ─────────────
  { id:46, initiative:'Develop Our Talent Infrastructure', category:'Systems & People',
    title:'Competency Model Development', owner:'Dan S.',
    status:'On Track', percentComplete:40,
    q1Goals:'Draft competency model for Analyst through Manager levels',
    q2Goals:'Model approved; piloted in performance conversations',
    q3Goals:'Competency model fully embedded in PM and development processes',
    latestComment:'Competency model complete for Consultant through Manager levels. Senior Manager and above in draft. Review session with leadership April 20th.',
    lastUpdatedBy:'Dan S.', modified:'2026-04-08' },

  { id:47, initiative:'Develop Our Talent Infrastructure', category:'Systems & People',
    title:'HRBP Model Design & Implementation', owner:'Ali F.',
    status:'On Track', percentComplete:30,
    q1Goals:'Define HRBP model; align with leadership on structure',
    q2Goals:'HRBP assignments made; onboarding complete',
    q3Goals:'HRBP model fully operational; manager satisfaction improving',
    latestComment:'HRBP model approved for H2 implementation. HRBP job descriptions finalized. Hiring process starting in May.',
    lastUpdatedBy:'Ali F.', modified:'2026-04-06' },

  { id:48, initiative:'Develop Our Talent Infrastructure', category:'Systems & People',
    title:'Performance Management Process Redesign', owner:'Dan S.',
    status:'On Track', percentComplete:25,
    q1Goals:'Document current PM process gaps; design new framework',
    q2Goals:'New PM process approved; manager training complete',
    q3Goals:'First full PM cycle on new process completed',
    latestComment:'Current process gaps documented. New framework drafted: quarterly check-ins, competency-based ratings, calibration process.',
    lastUpdatedBy:'Dan S.', modified:'2026-03-28' },

  { id:49, initiative:'Develop Our Talent Infrastructure', category:'Systems & People',
    title:'Skill Development Programs', owner:'Ali F.',
    status:'On Track', percentComplete:15,
    q1Goals:'Conduct firm-wide skill gap assessment; prioritize development areas',
    q2Goals:'Top 3 development programs launched',
    q3Goals:'Programs running at scale; skill improvements measured',
    latestComment:'Skill gap survey launching next week across all staff. L&D partnership options being explored.',
    lastUpdatedBy:'Ali F.', modified:'2026-04-08' },

  { id:50, initiative:'Develop Our Talent Infrastructure', category:'Systems & People',
    title:'Talent Assessment & Succession Planning', owner:'Dan S.',
    status:'On Track', percentComplete:20,
    q1Goals:'Complete current-state talent assessment; identify flight risk and high potentials',
    q2Goals:'Succession plans in place for key roles; retention actions underway',
    q3Goals:'Succession framework embedded in annual talent review',
    latestComment:'Manager interviews complete across all practice areas. High-potential identification framework drafted.',
    lastUpdatedBy:'Dan S.', modified:'2026-04-01' }

];

// ── Seed Update History (demo mode) ───────────────────────────────
const SEED_UPDATES = [
  { workstreamTitle:'Pod Model Design & Rollout', updatedBy:'Luke B.', status:'On Track', percentComplete:75, comment:'Pod Model V2 75% complete. Structure finalized: pods of 4-6 by solution area. Manager briefing April 27th.', created:'2026-04-07T14:22:00Z' },
  { workstreamTitle:'Pod Model Design & Rollout', updatedBy:'Luke B.', status:'On Track', percentComplete:45, comment:'V1 design complete and reviewed with Kevin. Good partner alignment. Moving to V2 with incorporation of feedback.', created:'2026-03-10T10:00:00Z' },
  { workstreamTitle:'Pod Model Design & Rollout', updatedBy:'Luke B.', status:'On Track', percentComplete:15, comment:'Kicked off. Benchmarking pod models from peer consulting firms. Initial design principles drafted.', created:'2026-01-28T09:00:00Z' },

  { workstreamTitle:'Staffing Governance Framework', updatedBy:'Aaron M.', status:'On Track', percentComplete:50, comment:'Governance framework draft complete. Decision rights matrix reviewed with Kevin. Staffing process redesign underway.', created:'2026-03-24T10:05:00Z' },
  { workstreamTitle:'Staffing Governance Framework', updatedBy:'Aaron M.', status:'On Track', percentComplete:20, comment:'Governance principles defined. Beginning decision rights mapping across account types.', created:'2026-02-15T10:00:00Z' },

  { workstreamTitle:'ACV Methodology & Bookings Targets', updatedBy:'Caden R.', status:'On Track', percentComplete:40, comment:'ACV methodology finalized and approved. Bookings targets set. Bi-weekly pipeline review established.', created:'2026-04-08T16:00:00Z' },
  { workstreamTitle:'ACV Methodology & Bookings Targets', updatedBy:'Caden R.', status:'On Track', percentComplete:20, comment:'Draft methodology under review with finance. Coverage ratio baseline: 2.1x.', created:'2026-03-05T13:00:00Z' },

  { workstreamTitle:'Solution Architect Role Definition', updatedBy:'Clare M.', status:'At Risk', percentComplete:10, comment:'Role defined but headcount approval stalled. Escalation needed by end of April.', created:'2026-04-10T08:30:00Z' },
  { workstreamTitle:'Solution Architect Role Definition', updatedBy:'Clare M.', status:'On Track', percentComplete:8, comment:'Role requirements drafted. Submitted headcount request to leadership.', created:'2026-03-01T09:00:00Z' },

  { workstreamTitle:'HubSpot \u2192 Sage Intacct Integration', updatedBy:'Patrick C.', status:'At Risk', percentComplete:20, comment:'Field mapping complete. API dev started but scope growing. At Risk due to deal attribution complexity.', created:'2026-04-09T15:00:00Z' },
  { workstreamTitle:'HubSpot \u2192 Sage Intacct Integration', updatedBy:'Patrick C.', status:'On Track', percentComplete:15, comment:'Integration architecture approved. Field mapping 80% complete.', created:'2026-03-22T14:00:00Z' },

  { workstreamTitle:'Training Curriculum Development', updatedBy:'Justin L.', status:'On Track', percentComplete:55, comment:'Pilot with 8 associates complete — 4.4/5 feedback. Modules 1-4 finalized.', created:'2026-04-07T13:30:00Z' },
  { workstreamTitle:'Training Curriculum Development', updatedBy:'Justin L.', status:'On Track', percentComplete:30, comment:'Modules 1-3 drafted. Pilot group of 8 associates identified.', created:'2026-03-15T10:00:00Z' },

  { workstreamTitle:'Risk Guardrail Framework', updatedBy:'Nicole B.', status:'On Track', percentComplete:45, comment:'Framework v1 approved by leadership. Training materials in development.', created:'2026-04-06T14:00:00Z' },
  { workstreamTitle:'Risk Guardrail Framework', updatedBy:'Nicole B.', status:'On Track', percentComplete:20, comment:'Draft guardrails covering data privacy and client confidentiality circulating for review.', created:'2026-03-10T11:00:00Z' },

  { workstreamTitle:'Competency Model Development', updatedBy:'Dan S.', status:'On Track', percentComplete:40, comment:'Complete through Manager level. Senior Manager draft in progress. Leadership review April 20th.', created:'2026-04-08T12:00:00Z' },
  { workstreamTitle:'Competency Model Development', updatedBy:'Dan S.', status:'On Track', percentComplete:18, comment:'Analyst through Senior Associate levels complete. Consultant and Manager in progress.', created:'2026-03-12T10:00:00Z' },

  { workstreamTitle:'Time Capture & Resource Management', updatedBy:'Luke B.', status:'At Risk', percentComplete:10, comment:'Requirements gathering revealed complexity with pod model intersection. ~3 week delay. At Risk.', created:'2026-04-09T15:30:00Z' },

  { workstreamTitle:'Competitive Landscape Analysis', updatedBy:'Piotr W.', status:'On Track', percentComplete:35, comment:'Review complete across 5 vendors. Three key gaps: Databricks integration, AI validation, modern MDM.', created:'2026-04-05T09:45:00Z' },

  { workstreamTitle:'Technology Asset Inventory', updatedBy:'Jason K.', status:'On Track', percentComplete:40, comment:'14 reusable components identified across Arc, Mainsail, IC. Library being formatted for publication.', created:'2026-04-04T16:00:00Z' }
];
