// ═══════════════════════════════════════════════════════
//  config.js – 2026 Firm Building Initiatives Dashboard
// ═══════════════════════════════════════════════════════

const CONFIG = {
  clientId:    '8abbd6c0-4717-4220-b6c1-a38dae7c3a14',
  tenantId:    '4854ac27-6418-4983-9efc-93545436d559',
  redirectUri: 'https://conroy-patrick.github.io/2026-firm-building-initiatives/',
  graphEndpoint:      'https://graph.microsoft.com/v1.0',
  siteHostname:       'beghouconsultinginc-my.sharepoint.com',
  sitePath:           '/personal/aaron_mccracken_beghouconsulting_com',
  wsListName:         '2026 Initiative Tracker',
  updatesListName:    'Initiative Updates',
  fiscalYearStart:    new Date('2026-01-01'),
  fiscalYearEnd:      new Date('2026-12-31'),
  refreshIntervalMs:  5 * 60 * 1000
};

CONFIG.expectedProgress = (() => {
  const now = new Date(), s = CONFIG.fiscalYearStart, e = CONFIG.fiscalYearEnd;
  return Math.round((Math.max(0, Math.min(now - s, e - s)) / (e - s)) * 100);
})();

// ── Initiative metadata (descriptions, goals, owners) ────────────
const SEED_INITIATIVES = [
  { id:1, title:'Bookings Sufficient to Achieve Target',            category:'Revenue & Operations', accountablePartner:'Dennis',         execSponsor:'MR', q1Goals:'Define ACV methodology; baseline pipeline health', q2Goals:'Pipeline framework live; RFP tracking operational', q3Goals:'Full KPI reporting live; mid-year review complete' },
  { id:2, title:'Commercial Infrastructure & Sustainable Growth',   category:'Revenue & Operations', accountablePartner:'Clare',           execSponsor:'MR', q1Goals:'Sales ops audit; RFP assessment complete',         q2Goals:'Solution architect hired; training program launched',q3Goals:'Full commercial infrastructure operational' },
  { id:3, title:'Effective Workforce Planning & Deployment',        category:'Revenue & Operations', accountablePartner:'Kevin',           execSponsor:'MR', q1Goals:'Leadership alignment complete; teams assembled',    q2Goals:'Staffing model finalized; all workstreams by 5/31', q3Goals:'Pod model live; performance frameworks active' },
  { id:4, title:'Deliverable Quality',                              category:'Revenue & Operations', accountablePartner:'TBD',             execSponsor:'MR', q1Goals:'Assign accountable partner; scope workstreams',     q2Goals:'QC framework defined; KM platform selected',       q3Goals:'Templates, training, and QC processes live' },
  { id:5, title:'AI Strategy for Internal Use (L1\u2013L3)',        category:'Revenue & Operations', accountablePartner:'Nicole',          execSponsor:'MR', q1Goals:'Risk guardrails drafted; AI tool inventory done',   q2Goals:'Toolkit standards published; L1 workflows live',   q3Goals:'L2\u2013L3 automation deployed firm-wide' },
  { id:6, title:'Future-Proofing Data Management Offering',         category:'Product & Tech',       accountablePartner:'Piotr',           execSponsor:'DC', q1Goals:'Competitive landscape review; roadmap scoped',      q2Goals:'Priority roadmap items in development',            q3Goals:'Key milestones delivered; offering reviewed' },
  { id:7, title:'Technology Strategy for Scale & Profit',           category:'Product & Tech',       accountablePartner:'Jason',           execSponsor:'DC', q1Goals:'Technology asset inventory; ROI framework defined', q2Goals:'Prioritized roadmap with ROI modeling published',  q3Goals:'Top technologies in development or deployed' },
  { id:8, title:'Optimizing Arc Data Management Delivery',          category:'Product & Tech',       accountablePartner:'Justin',          execSponsor:'DC', q1Goals:'Training curriculum defined; hiring plan final',    q2Goals:'Delivery center pilot launched; first cohort trained',q3Goals:'Full delivery center operational' },
  { id:9, title:'Beghou Unified Systems Success',                   category:'Systems & People',     accountablePartner:'Yair (w/ Michael)',execSponsor:'MG', q1Goals:'Requirements final; vendor selected; arch approved', q2Goals:'Integration development and testing underway',     q3Goals:'Go-live active; finance sign-off complete' },
  { id:10,title:'Develop Our Talent Infrastructure',                category:'Systems & People',     accountablePartner:'Dan S (w/ Ali)',  execSponsor:'AF', q1Goals:'Competency model framework drafted; assessment done',q2Goals:'Performance management defined; pilot launched',   q3Goals:'Full talent infrastructure live; programs active' }
];

// ── Workstream seed data (50 workstreams, ~5 per initiative) ─────
const SEED_WORKSTREAMS = [
  // ── Initiative 1: Bookings ──────────────────────────────────────
  { id:'ws-1-1', initiativeId:1, category:'Revenue & Operations', title:'ACV Methodology & Bookings Targets',    owner:'Caden R.',  status:'On Track',    percentComplete:50, description:'Define and finalize the ACV calculation methodology, establish H1/H2 bookings targets, and align with finance on measurement approach.', latestComment:'ACV methodology finalized and approved by finance. H1 and H2 targets communicated to all partners.', lastUpdatedBy:'Caden R.',  modified:'2026-04-08' },
  { id:'ws-1-2', initiativeId:1, category:'Revenue & Operations', title:'Pipeline Management & Review Cadence',  owner:'Caden R.',  status:'On Track',    percentComplete:35, description:'Establish a structured pipeline review process with defined cadence, stage criteria, and coverage ratio targets for forward-looking visibility.', latestComment:'Bi-weekly pipeline reviews established. Coverage ratio at 2.1x target. Stage entry criteria being finalized.', lastUpdatedBy:'Caden R.',  modified:'2026-03-28' },
  { id:'ws-1-3', initiativeId:1, category:'Revenue & Operations', title:'New Logo Acquisition Strategy',         owner:'Dennis P.', status:'On Track',    percentComplete:20, description:'Develop a targeted new logo strategy including prospect identification, outreach approach, and conversion milestones for 2026.', latestComment:'Target list of 15 new logo prospects identified. Outreach strategy in development with BD team.', lastUpdatedBy:'Dennis P.', modified:'2026-03-15' },
  { id:'ws-1-4', initiativeId:1, category:'Revenue & Operations', title:'RFP Tracking & Win/Loss Analysis',      owner:'Caden R.',  status:'On Track',    percentComplete:25, description:'Implement a systematic approach to tracking RFP volume, win rates, and loss reasons to inform commercial strategy and improve conversion.', latestComment:'RFP tracking template live. Win/loss analysis framework being built — first report targeting Q2.', lastUpdatedBy:'Caden R.',  modified:'2026-04-01' },
  { id:'ws-1-5', initiativeId:1, category:'Revenue & Operations', title:'Sales KPI Dashboard & Reporting',       owner:'Caden R.',  status:'Not Started', percentComplete:5,  description:'Build a real-time KPI dashboard for sales leadership tracking bookings, pipeline, new logos, and ACV Book to Bill ratio.', latestComment:'Dashboard requirements drafted. Awaiting final KPI sign-off from MR before development begins.', lastUpdatedBy:'Caden R.',  modified:'2026-03-20' },

  // ── Initiative 2: Commercial Infrastructure ─────────────────────
  { id:'ws-2-1', initiativeId:2, category:'Revenue & Operations', title:'Sales Operations Audit & Optimization', owner:'Mudit S.',  status:'On Track',    percentComplete:30, description:'Conduct a comprehensive audit of current sales operations and implement optimizations across account planning, pipeline, and sales process.', latestComment:'Audit complete. Key gaps: inconsistent account planning across partners, no standardized pricing playbook. Optimization plan in development.', lastUpdatedBy:'Mudit S.',  modified:'2026-04-02' },
  { id:'ws-2-2', initiativeId:2, category:'Revenue & Operations', title:'RFP Process Excellence',                owner:'Adriana V.',status:'On Track',    percentComplete:20, description:'Redesign the RFP response process to improve quality, reduce turnaround time, and increase win rates through standardized templates and review workflows.', latestComment:'RFP process assessment complete. New template and review workflow targeting Q2 launch.', lastUpdatedBy:'Adriana V.',modified:'2026-03-30' },
  { id:'ws-2-3', initiativeId:2, category:'Revenue & Operations', title:'Solution Architect Role & Hiring',      owner:'Clare M.',  status:'At Risk',     percentComplete:10, description:'Define the Solution Architect role requirements, compensation, and hiring plan to support large deal pursuit and technical sales engagements.', latestComment:'Role definition drafted but stalled pending headcount approval. At Risk — exec decision needed by end of April.', lastUpdatedBy:'Clare M.',  modified:'2026-04-10' },
  { id:'ws-2-4', initiativeId:2, category:'Revenue & Operations', title:'Large Account Management Framework',    owner:'Luke B.',   status:'On Track',    percentComplete:15, description:'Implement a structured LAM framework including account plans, QBRs, and growth tracking for Beghou top 10 accounts.', latestComment:'LAM framework drafted. Account plan template in review with two pilot partners. QBR structure being defined.', lastUpdatedBy:'Luke B.',   modified:'2026-03-25' },
  { id:'ws-2-5', initiativeId:2, category:'Revenue & Operations', title:'Pricing Discipline & Playbook',         owner:'Mudit S.',  status:'Not Started', percentComplete:5,  description:'Develop a pricing playbook establishing rate card standards, discount authority levels, and margin floor guidance across all service lines.', latestComment:'Pricing audit scheduled for May. Playbook design not yet started — dependent on sales ops audit findings.', lastUpdatedBy:'Mudit S.',  modified:'2026-03-10' },

  // ── Initiative 3: Workforce Planning ────────────────────────────
  { id:'ws-3-1', initiativeId:3, category:'Revenue & Operations', title:'Pod Model Design & Implementation',     owner:'Kevin F.',  status:'On Track',    percentComplete:75, description:'Design and implement a pod-based delivery model organizing associates into cross-functional teams aligned to client accounts and solution areas.', latestComment:'Pod model V2 due 4/15. Structure finalized for Life Sciences Commercial and Data practices. Rollout plan being drafted.', lastUpdatedBy:'Kevin F.',  modified:'2026-04-07' },
  { id:'ws-3-2', initiativeId:3, category:'Revenue & Operations', title:'Staffing Governance Framework',         owner:'Aaron M.',  status:'On Track',    percentComplete:50, description:'Establish a staffing governance framework including resource request processes, utilization targets, bench management, and partner accountability standards.', latestComment:'Governance framework 50% complete. Resource request process and utilization targets defined. Bench management standards in draft.', lastUpdatedBy:'Aaron M.',  modified:'2026-03-24' },
  { id:'ws-3-3', initiativeId:3, category:'Revenue & Operations', title:'Performance Management Standards',      owner:'Dan K.',    status:'On Track',    percentComplete:35, description:'Define performance management standards for delivery quality, client satisfaction, and individual contribution tied to the new pod model structure.', latestComment:'Competency-based performance standards drafted for Manager and Senior Associate levels. Associate level in progress.', lastUpdatedBy:'Dan K.',    modified:'2026-03-20' },
  { id:'ws-3-4', initiativeId:3, category:'Revenue & Operations', title:'US-India Collaboration Model',          owner:'Luke B.',   status:'On Track',    percentComplete:30, description:'Design a structured collaboration model between US and India teams including work allocation principles, communication protocols, and quality standards.', latestComment:'Collaboration model framework drafted. Pilot team of 6 identified across two client accounts. Kick-off scheduled for May.', lastUpdatedBy:'Luke B.',   modified:'2026-03-18' },
  { id:'ws-3-5', initiativeId:3, category:'Revenue & Operations', title:'Change Management & Communications',    owner:'Kevin F.',  status:'On Track',    percentComplete:40, description:'Lead the change management and internal communications strategy for the workforce redesign, ensuring partner and associate buy-in and smooth transition.', latestComment:'Manager briefing April 27th, All Hands May 5th. FAQ and talking points drafted. Pulse survey scheduled for June.', lastUpdatedBy:'Kevin F.',  modified:'2026-04-07' },

  // ── Initiative 4: Deliverable Quality ───────────────────────────
  { id:'ws-4-1', initiativeId:4, category:'Revenue & Operations', title:'Knowledge Management Platform',         owner:'TBD',       status:'Behind',      percentComplete:5,  description:'Select, configure, and launch a knowledge management platform to house deliverable templates, best practices, and institutional knowledge.', latestComment:'Platform not yet selected. Accountable owner not assigned. Behind on Q1 goal.', lastUpdatedBy:'MR',        modified:'2026-04-09' },
  { id:'ws-4-2', initiativeId:4, category:'Revenue & Operations', title:'QC Process & Review Standards',         owner:'TBD',       status:'Behind',      percentComplete:0,  description:'Design and implement quality control processes and peer review standards to ensure consistency and excellence across all client deliverables.', latestComment:'Not started. Awaiting accountable partner assignment before this workstream can begin.', lastUpdatedBy:'MR',        modified:'2026-04-09' },
  { id:'ws-4-3', initiativeId:4, category:'Revenue & Operations', title:'Solutions Templates Library',           owner:'TBD',       status:'Not Started', percentComplete:0,  description:'Build a curated library of reusable deliverable templates across all of Beghou solution areas, standardizing format and quality.', latestComment:'Not started. Template inventory will begin once KM platform is selected.', lastUpdatedBy:'MR',        modified:'2026-02-01' },
  { id:'ws-4-4', initiativeId:4, category:'Revenue & Operations', title:'Training & Onboarding Program',         owner:'TBD',       status:'Not Started', percentComplete:0,  description:'Develop a structured training and onboarding program covering Beghou quality standards, deliverable expectations, and client communication protocols.', latestComment:'Not started. Dependent on QC standards being defined first.', lastUpdatedBy:'MR',        modified:'2026-02-01' },
  { id:'ws-4-5', initiativeId:4, category:'Revenue & Operations', title:'Project Documentation Standards',       owner:'TBD',       status:'Behind',      percentComplete:10, description:'Define and enforce project documentation standards including SOW templates, status reporting formats, and project closure requirements.', latestComment:'Existing standards inventoried as baseline. No active development — awaiting initiative owner assignment.', lastUpdatedBy:'MR',        modified:'2026-03-15' },

  // ── Initiative 5: AI Strategy ───────────────────────────────────
  { id:'ws-5-1', initiativeId:5, category:'Revenue & Operations', title:'AI Objectives & Risk Guardrail Framework',owner:'Nicole B.',status:'On Track',   percentComplete:60, description:'Define Beghou AI objectives for internal use, establish risk guardrails, data privacy guidelines, and acceptable use policy across all workflow levels.', latestComment:'Framework v1 approved by leadership. Rollout communications drafted. Data privacy guidelines finalized with legal.', lastUpdatedBy:'Nicole B.', modified:'2026-04-06' },
  { id:'ws-5-2', initiativeId:5, category:'Revenue & Operations', title:'AI Tool Inventory & Standardization',   owner:'Sharath N.',status:'On Track',   percentComplete:50, description:'Inventory all AI tools currently in use across Beghou, evaluate against approved criteria, and consolidate to a standardized toolkit by practice area.', latestComment:'11 distinct tools identified. Consolidating to 4 approved platforms. Sunset plan for non-approved tools being drafted.', lastUpdatedBy:'Sharath N.',modified:'2026-04-01' },
  { id:'ws-5-3', initiativeId:5, category:'Revenue & Operations', title:'L1 Workflow Automation',                owner:'Sharath N.',status:'On Track',   percentComplete:25, description:'Identify, prioritize, and automate Level 1 internal workflows — primarily administrative and repetitive tasks — using approved AI tools.', latestComment:'L1 workflows fully mapped. Top 5 automation candidates selected. Implementation begins Q2.', lastUpdatedBy:'Sharath N.',modified:'2026-03-28' },
  { id:'ws-5-4', initiativeId:5, category:'Revenue & Operations', title:'L2\u2013L3 Workflow Automation',         owner:'Sharath N.',status:'Not Started',percentComplete:5,  description:'Scope and implement AI automation for Level 2 and 3 workflows involving analysis, synthesis, and judgment-intensive tasks.', latestComment:'Pending L1 workstream completion. Scoping sessions scheduled to begin in Q2.', lastUpdatedBy:'Nicole B.', modified:'2026-02-15' },
  { id:'ws-5-5', initiativeId:5, category:'Revenue & Operations', title:'Knowledge Sharing & Training Program',  owner:'Nicole B.',status:'On Track',   percentComplete:20, description:'Build a firm-wide AI knowledge sharing program including monthly showcases, use case library, and structured training for all staff levels.', latestComment:'Monthly AI Showcase series launched — 2 sessions completed with 40+ attendees each. Use case library being built.', lastUpdatedBy:'Nicole B.', modified:'2026-03-20' },

  // ── Initiative 6: Data Management Offering ──────────────────────
  { id:'ws-6-1', initiativeId:6, category:'Product & Tech',       title:'Competitive Landscape & Market Analysis',owner:'Piotr W.', status:'On Track',   percentComplete:40, description:'Conduct a comprehensive competitive analysis of data management offerings from Veeva, IQVIA, and Symphony to identify differentiation opportunities.', latestComment:'Veeva, IQVIA, Symphony analysis complete. Final report drafted for DC review. Three differentiation opportunities identified.', lastUpdatedBy:'Piotr W.', modified:'2026-04-05' },
  { id:'ws-6-2', initiativeId:6, category:'Product & Tech',       title:'Databricks Migration Support Roadmap',   owner:'Piotr W.', status:'On Track',   percentComplete:20, description:'Define Beghou Databricks migration support offering including methodology, tooling requirements, and client delivery model.', latestComment:'Roadmap scoped. Three client opportunities identified for 2026. Technical requirements being gathered.', lastUpdatedBy:'Piotr W.', modified:'2026-03-28' },
  { id:'ws-6-3', initiativeId:6, category:'Product & Tech',       title:'MDM Modernization Roadmap',              owner:'Piotr W.', status:'On Track',   percentComplete:15, description:'Develop a modernized MDM offering roadmap addressing next-generation master data architecture, governance, and AI-enhanced data quality.', latestComment:'Requirements gathering sessions scheduled with 4 active client accounts. Roadmap draft expected end of Q2.', lastUpdatedBy:'Piotr W.', modified:'2026-03-20' },
  { id:'ws-6-4', initiativeId:6, category:'Product & Tech',       title:'AI-Assisted Data Validation',            owner:'Piotr W.', status:'Not Started',percentComplete:5,  description:'Design and build AI-assisted data validation capabilities embedded into Beghou data management delivery to improve quality and reduce manual effort.', latestComment:'Concept approved by DC. Technical feasibility assessment scheduled for Q2. No development started.', lastUpdatedBy:'Piotr W.', modified:'2026-02-20' },
  { id:'ws-6-5', initiativeId:6, category:'Product & Tech',       title:'Client Delivery Commitment Mapping',     owner:'Piotr W.', status:'On Track',   percentComplete:20, description:'Map all 2026 client delivery commitments related to data management to ensure roadmap supports in-year obligations without creating delivery risk.', latestComment:'2026 DM delivery commitments mapped for 8 active clients. Two accounts flagged as having roadmap dependency — escalated to DC.', lastUpdatedBy:'Piotr W.', modified:'2026-04-01' },

  // ── Initiative 7: Technology Strategy ───────────────────────────
  { id:'ws-7-1', initiativeId:7, category:'Product & Tech',       title:'Technology Asset Inventory',             owner:'Jason K.', status:'On Track',   percentComplete:60, description:'Catalog all existing technology assets, reusable components, and IP across Arc, Mainsail, IC, and other platforms to identify leverage opportunities.', latestComment:'14 reusable components identified across Arc, Mainsail, and IC platforms. Documentation complete. ROI analysis underway.', lastUpdatedBy:'Jason K.', modified:'2026-04-04' },
  { id:'ws-7-2', initiativeId:7, category:'Product & Tech',       title:'ROI Framework & Modeling',               owner:'Jason K.', status:'On Track',   percentComplete:35, description:'Build an ROI framework and financial model for technology investments that quantifies profit impact of reuse and informs prioritization decisions.', latestComment:'ROI framework v1 drafted. Under review with DC and finance. Expected approval by end of April.', lastUpdatedBy:'Jason K.', modified:'2026-03-30' },
  { id:'ws-7-3', initiativeId:7, category:'Product & Tech',       title:'Reusable Component Prioritization',      owner:'Jason K.', status:'On Track',   percentComplete:20, description:'Score and prioritize reusable technology components based on reuse potential, development effort, and profit impact to build the 2026 investment roadmap.', latestComment:'Scoring criteria defined and approved. Top 5 components being evaluated for prioritization.', lastUpdatedBy:'Jason K.', modified:'2026-03-22' },
  { id:'ws-7-4', initiativeId:7, category:'Product & Tech',       title:'Arc Platform Scalability Roadmap',       owner:'Jason K.', status:'On Track',   percentComplete:15, description:'Define Arc platform scalability requirements and roadmap to support 3x client volume growth without proportional cost increase.', latestComment:'Roadmap inputs gathered from product team and top clients. Draft roadmap in progress — targeting Q2 completion.', lastUpdatedBy:'Jason K.', modified:'2026-03-15' },
  { id:'ws-7-5', initiativeId:7, category:'Product & Tech',       title:'Technology Governance & Standards',      owner:'Jason K.', status:'Not Started',percentComplete:5,  description:'Establish technology governance standards covering build vs. buy decisions, tech stack standards, and reuse requirements for all new development.', latestComment:'Governance charter not yet drafted. Scheduled to begin Q2 after ROI framework finalized.', lastUpdatedBy:'Jason K.', modified:'2026-02-10' },

  // ── Initiative 8: Arc DM Delivery ───────────────────────────────
  { id:'ws-8-1', initiativeId:8, category:'Product & Tech',       title:'Training Curriculum Development',        owner:'Justin L.',status:'On Track',   percentComplete:70, description:'Develop a comprehensive training curriculum for Arc DM delivery covering data architecture, platform tooling, client engagement standards, and QA processes.', latestComment:'Curriculum piloted with 8 associates — strong feedback. Modules 4 and 5 being finalized based on pilot learnings.', lastUpdatedBy:'Justin L.',modified:'2026-04-07' },
  { id:'ws-8-2', initiativeId:8, category:'Product & Tech',       title:'Strategic Hiring Plan',                  owner:'Justin L.',status:'On Track',   percentComplete:50, description:'Build and execute a strategic hiring plan to staff the Arc DM delivery center with 4 new roles in H1 targeting Databricks, Veeva, and MDM skills.', latestComment:'4 new DM roles approved. JDs posted and interviews underway. First hire expected by May 15th.', lastUpdatedBy:'Justin L.',modified:'2026-04-05' },
  { id:'ws-8-3', initiativeId:8, category:'Product & Tech',       title:'Delivery Center Launch',                 owner:'Justin L.',status:'On Track',   percentComplete:30, description:'Launch a dedicated Arc DM delivery center with defined team structure, capacity model, and quality standards as the primary delivery engine.', latestComment:'Location and team structure confirmed. Pilot kicks off May 1st with 3 initial accounts. Onboarding plan finalized.', lastUpdatedBy:'Justin L.',modified:'2026-04-07' },
  { id:'ws-8-4', initiativeId:8, category:'Product & Tech',       title:'Resource Planning Model',                owner:'Justin L.',status:'On Track',   percentComplete:25, description:'Build a resource planning model for Arc DM delivery that projects capacity needs, manages utilization, and aligns staffing to pipeline demand.', latestComment:'Resource model v1 drafted. Capacity planning assumptions being validated against Q2/Q3 pipeline. Final model by May 31.', lastUpdatedBy:'Justin L.',modified:'2026-03-25' },
  { id:'ws-8-5', initiativeId:8, category:'Product & Tech',       title:'Efficiency Metrics & Reporting',         owner:'Justin L.',status:'Not Started',percentComplete:10, description:'Define and implement efficiency metrics for Arc DM delivery including utilization rates, delivery cycle times, rework rates, and client satisfaction scores.', latestComment:'KPIs defined and approved. Dashboard build not yet started — scheduled for Q2 after delivery center pilot launches.', lastUpdatedBy:'Justin L.',modified:'2026-03-10' },

  // ── Initiative 9: Unified Systems ───────────────────────────────
  { id:'ws-9-1', initiativeId:9, category:'Systems & People',     title:'System Requirements & Architecture',     owner:'Yair S.',  status:'On Track',   percentComplete:90, description:'Finalize all system requirements across capacity planning, revenue recognition, resource management, time capture, and invoicing. Define integration architecture.', latestComment:'Requirements 90% complete. Integration architecture approved by Michael G. Final open items: time capture edge cases being resolved.', lastUpdatedBy:'Yair S.',   modified:'2026-04-09' },
  { id:'ws-9-2', initiativeId:9, category:'Systems & People',     title:'HubSpot \u2192 Sage Intacct Integration', owner:'Patrick C.',status:'On Track',  percentComplete:35, description:'Build and test the HubSpot to Sage Intacct integration for automated revenue recognition, covering deal close, line-item sync, and invoice generation.', latestComment:'Field mapping complete. Development underway — deal close trigger and line-item sync being built. QA environment set up.', lastUpdatedBy:'Patrick C.',modified:'2026-03-22' },
  { id:'ws-9-3', initiativeId:9, category:'Systems & People',     title:'Ruddr Resource Management Integration',  owner:'Patrick C.',status:'At Risk',   percentComplete:20, description:'Integrate Ruddr with the unified systems platform for real-time resource management, utilization tracking, and capacity planning.', latestComment:'API scoping revealed higher complexity — webhook limitations require custom polling solution. Estimating 3-week delay.', lastUpdatedBy:'Patrick C.',modified:'2026-04-09' },
  { id:'ws-9-4', initiativeId:9, category:'Systems & People',     title:'Time Capture Module',                    owner:'Yair S.',  status:'At Risk',   percentComplete:10, description:'Implement time capture functionality integrated with Ruddr and Sage Intacct to support accurate billing, utilization reporting, and project accounting.', latestComment:'Scoping revealed significant complexity around historical data migration. Timeline impact under assessment — likely 3+ week delay.', lastUpdatedBy:'Yair S.',   modified:'2026-04-09' },
  { id:'ws-9-5', initiativeId:9, category:'Systems & People',     title:'Go-Live & Change Management',            owner:'Yair S.',  status:'Not Started',percentComplete:5, description:'Plan and execute the go-live for the unified systems platform including user training, data migration validation, parallel run period, and adoption monitoring.', latestComment:'Dependent on integration workstreams completing. Go-live planning not started — expected to begin Q3.', lastUpdatedBy:'Michael G.', modified:'2026-02-01' },

  // ── Initiative 10: Talent Infrastructure ────────────────────────
  { id:'ws-10-1',initiativeId:10,category:'Systems & People',     title:'Competency Model Development',           owner:'Dan S.',   status:'On Track',   percentComplete:45, description:'Build a comprehensive competency model defining skills, behaviors, and performance expectations for all Beghou roles from Analyst through Partner.', latestComment:'Competency model complete for Consultant through Manager levels. Senior Associate and Partner levels in progress.', lastUpdatedBy:'Dan S.',    modified:'2026-04-08' },
  { id:'ws-10-2',initiativeId:10,category:'Systems & People',     title:'HRBP Model & Structure',                 owner:'Ali F.',   status:'On Track',   percentComplete:35, description:'Design and implement an HR Business Partner model to provide dedicated talent support to each practice area, improving manager effectiveness and associate development.', latestComment:'HRBP model design approved by leadership for H2 implementation. HRBP role JDs being drafted. Budget confirmed.', lastUpdatedBy:'Ali F.',    modified:'2026-04-05' },
  { id:'ws-10-3',initiativeId:10,category:'Systems & People',     title:'Performance Management Redesign',        owner:'Ali F.',   status:'On Track',   percentComplete:25, description:'Redesign Beghou performance management to align with the competency model, introduce continuous feedback, and modernize the annual review cycle.', latestComment:'Platform evaluation complete: Lattice selected over Leapsome. Procurement in progress. Process design begins Q2.', lastUpdatedBy:'Ali F.',    modified:'2026-04-03' },
  { id:'ws-10-4',initiativeId:10,category:'Systems & People',     title:'Skill Development Programs',             owner:'Dan S.',   status:'On Track',   percentComplete:15, description:'Design and launch structured skill development programs targeting the top capability gaps identified through talent assessment, covering technical, analytical, and client skills.', latestComment:'Skill gap assessment survey launching next week to all managers. Program design will follow survey results — expected Q2.', lastUpdatedBy:'Dan S.',    modified:'2026-04-08' },
  { id:'ws-10-5',initiativeId:10,category:'Systems & People',     title:'Talent Assessment & Gap Analysis',       owner:'Dan S.',   status:'On Track',   percentComplete:20, description:'Conduct a firm-wide talent assessment to benchmark current capabilities against the competency model and identify priority skill gaps by practice area.', latestComment:'Manager-level assessment complete across all practice areas. Associate and Analyst assessment underway. Gap analysis report expected mid-May.', lastUpdatedBy:'Dan S.',    modified:'2026-04-06' }
];
